# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2ca5fcb270cb44a4846adeed6ec2f4d0"
name = "NetScore Loyalty Rewards"
application_url = "https://shopify-project-loyalty.onrender.com"
embedded = true
handle = "netscore-loyalty-rewards"

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,read_customers,write_customers,write_draft_orders,read_draft_orders,write_inventory,read_inventory,read_orders,write_orders,read_products,write_products,write_price_rules,read_script_tags,write_script_tags"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://shopify-project-loyalty.onrender.com/auth/callback",
  "https://shopify-project-loyalty.onrender.com/api/auth/shopify-callback"
]
